### PR TITLE
Fix RTL bugs in several fragments/activities

### PR DESCRIPTION
**Pull request by cortinico**
This commit provide better RTL support for several screens.

- Items in list will have proper gravity based on user's Locale.
- The Collapsible toolbar on the Person Info Activity
will have the proper gravity based on the user's locale.

Here some before/after screenshots:

| Before | After |
| --- | --- |
| screenshot_1548538514 | screenshot_1548540448 |
| screenshot_1548540802 | screenshot_1548541330 |

### CODE REVIEW

**Comment by cbeyls** [comment]
Thank you for looking into this. I must say I don't know much about how Android handles RTL magic but I now started looking into it.

I think your styling fixes are a bit too radical. Putting view attributes in the app theme means that these attributes will be applied to every single view in the app which is always a bit dangerous. I started looking at how Google does it because the preferences screen of the app, which uses the preferences library now, displays elements properly aligned.

Also I would always prefer an XML solution to custom code when possible (about the fix for `CollapsingToolbarLayout`). Android has a special resource qualifier for RTL: `*-ldrtl` so you can specify the gravity there. But I'm not sure this is even needed in the first place because all Material components widgets are supposed to be RTL-ready out of the box, for example the `NavigationView` shows properly.

**Comment by cortinico** [comment]
> I think your styling fixes are a bit too radical. Putting view attributes in the app theme means that these attributes will be applied to every single view in the app which is always a bit dangerous. I started looking at how Google does it because the preferences screen of the app, which uses the preferences library now, displays elements properly aligned.

What about renaming `values-v17` to `values-ldrtl`?

> Also I would always prefer an XML solution to custom code when possible (about the fix for CollapsingToolbarLayout). Android has a special resource qualifier for RTL: *-ldrtl so you can specify the gravity there. 

So should we apply that fix on the XML level then?

> But I'm not sure this is even needed in the first place because all Material components widgets are supposed to be RTL-ready out of the box, for example the NavigationView shows properly.

Looks like the `CollapsingToolbarLayout` title is not :|

**Comment by cbeyls** [comment]
This is what I understood so far:

`android:textDirection` tells how the text is supposed to be read. It depends on the text content by default and you normally never need to change the default value.

`android:textAlignment` tells how the text is aligned in its container. By default this value is inherited from the parent, and if not available it is set to `gravity`. When set to `gravity`, it looks for the gravity, which is compared to the paragraph alignment, which depends on the `textDirection`, which means that the alignment will depend on the text language (English will always be aligned to the left and hebrew to the right for example). So I believe the proper fix is to set the `android:textDirection` to `viewStart` in a few key places, so instead of aligning with the text paragraph it aligns with the layout direction. This is mosly important for list items and `TextView`s with compound drawables, but the main content blocks which take the full width (like the talk description) should still be aligned according to the language and not to the layout.

Also, the ViewPager is always LTR, even in RTL mode. I heard a new ViewPager is being developed but it's not ready yet so I'll have to integrate a workaround for this too.

**Comment by cbeyls** [comment]
I don't plan to support RTL for API < 17
And yes we can add the attribute to the base layouts even if it's only available in API 17+, AAPT2 takes care of versioning the layouts in the APK file.

**Comment by cortinico** [comment]
@cbeyls Can you take a look at b817347 and let me know if you're ok with that approach?

**Pull request closed without merging**
